--- #YAML:1.0
name:               Dpchrist-ShellScript
version:            1.008
abstract:           utility functions for shell scripts
author:
    - David Christensen <dpchrist@holgerdanske.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Capture::Tiny:     0
    Dpchrist::Debug:   1.036
    Dpchrist::Module:  1.016
    Env::PS1:          0
    feature:           0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
